databases:
  - name: postgres
    ipAllowList: []
    databaseName: gran_sonrisa
    user: gran_sonrisa

services:
  - type: web
    name: gran_sonrisa
    env: ruby
    buildCommand: './render-build.sh'
    startCommand: 'bundle exec rails s'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
